### ISSUE TITLE
【機能要望】ニコサポにおいて、ポップアップウィンドウをピン止めしたい。

### ISSUE THREAD

**Issue by sahya** [yurafuca/nicosapo#26]
ニコサポにおいて、ポップアップウィンドウをピン止めしたい。

以下のウィンドウ全体を捜査しても、一時的にピン止めして閉じ名ようにしたいです。
![image](https://user-images.githubusercontent.com/1390632/79298941-8e83c180-7f1d-11ea-9773-e9db51d5bf82.png)

一時的に複数の放送を開きたいときがあるが、現時点では開いては閉じ開いては閉じをしなければいけない状態です。
もし可能であれば、搭載していただけると嬉しいです。

**Comment by yurafuca** [comment]
ご要望ありがとうございます👐

たいへん申し訳ありませんが，ポップアップが閉じられるのを防ぐ手段がないためご要望の機能を実装できません．

https://developer.chrome.com/extensions/faq#faq-persist-popups
> Can extensions open browser/page action popups without user interaction?
> No, popups can only be opened if the user clicks on the corresponding page or browser action. An extension cannot open its popup programatically.

複数の番組を一挙に開くための方法として，ポップアップをタブとして開く方法があります．下記の URL にアクセスしてみてください．本来であればポップアップに表示される内容がタブとして表示されます．

chrome-extension://kfnogdokhemdbbclknmmjpcnmjmpjknc/html/popup.html

この URL はブックマークに登録することもできます．

一方で，ポップアップをタブとして開くのは本来の使用方法ではありません．レイアウトが崩れていますし，この URL についても予告なく変わるかもしれません．
これらに留意した上でおためしください．

**Comment by sahya** [comment]
諸々、了解しました。ご教示ありがとうございます。
