### ISSUE TITLE
v6.0.0 のソースコードが push されていない

### ISSUE THREAD

**Issue by Thiry1** [yurafuca/nicosapo#28]
いくつか PR を出せたらと思っているので最新のソースを push していただけると嬉しいです

**Comment by ndxbn** [comment]
ちなみに、「にこさぽ v6.0.0 をリリース」されたのは2020年5月25日です。
https://twitter.com/yurafuca/status/1264873145376243713

master にマージされてないだけなのかと思ってブランチを見てみたけれど、そんなことはなく、push されてないようでした。

**Comment by yurafuca** [comment]
お返事が遅れてしまってすみません 🙇

v6.0.0 のコミットを push しました．
レガシーなコードがたくさん残っていて恥ずかしいですがよろしくお願いします……．

**Comment by Thiry1** [comment]
push されていることを確認しました。お忙しい中ありがとうございました！
