### ISSUE TITLE
多分6.0.0あたり？から自動入場に登録したユーザーが自動入場ができない

### ISSUE THREAD

**Issue by monokuro9770** [yurafuca/nicosapo#32]
タイトル通りです。どういう不具合か少し調べてみたんですけど、
コミュニティ画面の「(このユーザに) 自動入場: オン」で自動入場リストに登録すると、
ＵＲＬがコミュニティの番号ではなくそのコミュ主のユーザーIDの番号が登録されてるみたいです。
オプションの自動入場リスト（ユーザ）で確認しました。
例　コミュ番号 :co111111
　　ユーザーID :user/222222
　　登録されるURL :co222222

**Comment by yurafuca** [comment]
ありがとうございます．v6.0.0 でコミュニティベースの管理からユーザベースの管理に移行したので，コミュニティの id ではなくユーザの id が登録されるのはただしい挙動です．

それにもかかわらず自動入場できないのはおそらくユーザの配信状況を取得するのに失敗しているからだと思います．getplayerstatus という API を使って配信状況を取得しているのですが，この API はコミュニティの id には対応しているのですがユーザの id には対応していません．自動入場に失敗しているのはおそらくそのためです．

Related: https://github.com/yurafuca/nicosapo/issues/33

修正するためにはユーザの配信状況を取得できる api を調査する必要があります．

**Comment by yurafuca** [comment]
> v6.0.0 でコミュニティベースの管理からユーザベースの管理に移行した

ユーザベースの管理方法に移行したのは '放送中の番組' ページからコミュニティの id をスクレイピングで取得できなかったからでした．しかしこの制約は #31 により解消されました．これにともない #37 でコミュニティベースの管理方法に戻し，v6.0.0 未満と同じ仕組みで自動入場されるようにしました．

昨日リリースした v6.0.1 にこれらの変更が反映されています．v6.0.1 以降で不具合が再現する場合は reopen してください．
